# response/docker-compose.dev.yml
# Khusus buat development Person C — standalone
version: '3.8'

services:
  thehive:
    image: strangebee/thehive:5.2
    container_name: thehive
    ports:
      - "9000:9000"
    volumes:
      - thehive_data:/opt/thehive/data
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=demo1234
      - WEBHOOK_URL=http://localhost:5678
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  thehive_data:
  n8n_data: